export const CARE_SALE_CATEGORIES = [
  {
    slug: "body-mist",
    nameEn: "Body Mist",
    nameAr: "بادي ميست",
    sortOrder: 2,
  },
  {
    slug: "facial-care",
    nameEn: "Facial Care",
    nameAr: "العناية بالوجه",
    sortOrder: 3,
  },
] as const;

export const CARE_SALE_PRODUCTS = [
  {
    slug: "hi-line-body-mist-candy-cloud",
    sku: "0788792462069",
    barcode: "0788792462069",
    categorySlug: "body-mist",
    nameEn: "Hi Line Body Mist - Candy Cloud",
    nameAr: "هاي لاين بادي ميست - كاندي كلاود",
    scent: "Candy Cloud",
    scentAr: "كاندي كلاود",
    scentColor: "#1769C2",
    image: "/products/hi-line-body-mist-candy-cloud.webp",
    descriptionEn: "Hi Line Body Mist Candy Cloud is a premium fragrance mist that provides long-lasting freshness and a silky skin feel.",
    descriptionAr: "هاي لاين بادي ميست كاندي كلاود معطر جسم فاخر يمنحك انتعاشًا يدوم طويلًا ويترك بشرتك بملمس ناعم كالحرير.",
    usageInstructions: "Shake well before use. Hold the bottle 10-15 cm away from the body and spray generously all over your body after showering or anytime throughout the day for an instant burst of freshness.",
    usageInstructionsAr: "رج العبوة جيدًا قبل الاستخدام. احمل الزجاجة على بُعد 10-15 سم من الجسم، ثم رش الرذاذ على كامل الجسم بعد الاستحمام أو في أي وقت طوال اليوم لتجديد الرائحة والانتعاش.",
  },
  {
    slug: "hi-line-body-mist-starry-night",
    sku: "0788792462076",
    barcode: "0788792462076",
    categorySlug: "body-mist",
    nameEn: "Hi Line Body Mist - Starry Night",
    nameAr: "هاي لاين بادي ميست - ستاري نايت",
    scent: "Starry Night",
    scentAr: "ستاري نايت",
    scentColor: "#C28A24",
    image: "/products/hi-line-body-mist-starry-night.webp",
    descriptionEn: "Hi Line Body Mist Starry Night is a premium fragrance mist that provides long-lasting freshness and a silky skin feel.",
    descriptionAr: "هاي لاين بادي ميست ستاري نايت معطر جسم فاخر يمنحك انتعاشًا يدوم طويلًا ويترك بشرتك بملمس ناعم كالحرير.",
    usageInstructions: "Shake well before use. Hold the bottle 10-15 cm away from the body and spray generously all over your body after showering or anytime throughout the day for an instant burst of freshness.",
    usageInstructionsAr: "رج العبوة جيدًا قبل الاستخدام. احمل الزجاجة على بُعد 10-15 سم من الجسم، ثم رش الرذاذ على كامل الجسم بعد الاستحمام أو في أي وقت طوال اليوم لتجديد الرائحة والانتعاش.",
  },
  {
    slug: "hi-line-body-mist-secret-touch",
    sku: "0788792462083",
    barcode: "0788792462083",
    categorySlug: "body-mist",
    nameEn: "Hi Line Body Mist - Secret Touch",
    nameAr: "هاي لاين بادي ميست - سيكريت تاتش",
    scent: "Secret Touch",
    scentAr: "سيكريت تاتش",
    scentColor: "#D71979",
    image: "/products/hi-line-body-mist-secret-touch.webp",
    descriptionEn: "Hi Line Body Mist Secret Touch is a premium fragrance mist that provides long-lasting freshness and a silky skin feel.",
    descriptionAr: "هاي لاين بادي ميست سيكريت تاتش معطر جسم فاخر يمنحك انتعاشًا يدوم طويلًا ويترك بشرتك بملمس ناعم كالحرير.",
    usageInstructions: "Shake well before use. Hold the bottle 10-15 cm away from the body and spray generously all over your body after showering or anytime throughout the day for an instant burst of freshness.",
    usageInstructionsAr: "رج العبوة جيدًا قبل الاستخدام. احمل الزجاجة على بُعد 10-15 سم من الجسم، ثم رش الرذاذ على كامل الجسم بعد الاستحمام أو في أي وقت طوال اليوم لتجديد الرائحة والانتعاش.",
  },
  {
    slug: "hi-line-cica-facial-cleanser",
    sku: "0788792462090",
    barcode: "0788792462090",
    categorySlug: "facial-care",
    nameEn: "Hi Line Cica Facial Cleanser",
    nameAr: "هاي لاين غسول السيكا جل للوجه",
    scent: "Fragrance Free",
    scentAr: "بدون عطر",
    scentColor: "#4A9F28",
    image: "/products/hi-line-cica-facial-cleanser.webp",
    descriptionEn: "Hi Line Cica Facial Cleanser helps to deeply cleanse the skin and remove makeup, featuring an advanced formula specially designed for oily and combination skin.",
    descriptionAr: "هاي لاين غسول السيكا جل يساعد على تنظيف البشرة بعمق وإزالة المكياج، بتركيبة متطورة مصممة خصيصًا للبشرة الدهنية والمختلطة.",
    usageInstructions: "Apply to wet face, gently massage for 60 seconds, then rinse thoroughly with water.",
    usageInstructionsAr: "يُوضع على الوجه المبلل، ويُدلك بلطف لمدة 60 ثانية، ثم يُشطف جيدًا بالماء.",
  },
] as const;

export const CARE_SALE_PRICE = {
  price: "299.00",
  salePrice: "224.00",
  discountPercent: 25,
} as const;
